benchmarks:
- freetype2-2017
- libpng-1.2.56
- harfbuzz-1.3.2
- openthread-2019-12-23
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: ttche
experiment_filestore: /tmp/experiment-data
fuzzers:
- aflplusplus_optimal
- mopt
- aflfast
- fairfuzz
- che_fuzz
git_hash: 57c0a4b1ab9ebc6d91d5152577084bcff85e7659
local_experiment: true
max_total_time: 180000
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
trials: 3
