benchmarks:
- freetype2-2017
- bloaty_fuzz_target
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: chefuzzer
experiment_filestore: /tmp/experiment-data
fuzzers:
- afl
- libfuzzer
- che_fuzz
git_hash: 40adb2d388ae01d9365b556f8fa60cbc5ba48de7
local_experiment: true
max_total_time: 60
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
trials: 1
