benchmarks:
- freetype2-2017
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: tttestfuzzer
experiment_filestore: /tmp/experiment-data
fuzzers:
- afl
- che_fuzz
git_hash: 4faf072e15fc3d14fb73284357271675bee41a57
local_experiment: true
max_total_time: 60
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
trials: 1
